### ISSUE TITLE
README Does Not Render Correctly on nuget.org

### ISSUE THREAD

**Issue by wbaldoumas** [wbaldoumas/atrea-policyengine#82]
## Description

The repository `README` does not render properly on [nuget.org](https://www.nuget.org/) at https://www.nuget.org/packages/Atrea.PolicyEngine/:

![image](https://user-images.githubusercontent.com/45316999/195680275-b8def2c7-3a90-4078-88bf-27282b006233.png)

This is likely due to the mix of HTML and Markdown not being supported there.

## Expected Behaviour

The README is rendered cleanly both on [github.com](https://github.com/) and [nuget.org](https://www.nuget.org/).

## Affected Version

v3.0.0

## Steps to Reproduce

Navigate to https://www.nuget.org/packages/Atrea.PolicyEngine/ and observe the issue.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wbaldoumas/atrea-policyengine/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by Rishabhraghwendra18** [comment]
Hi @wbaldoumas may I work on this issue ?

**Comment by wbaldoumas** [comment]
@Rishabhraghwendra18 go for it! 😄

**Comment by wbaldoumas** [comment]
Closing this, as it will be addressed once https://github.com/NuGet/NuGetGallery/issues/8644 is addressed.
